### ISSUE TITLE
New data publisher University of Modena and Reggio E. (Italy)

### ISSUE THREAD

**Issue by dagendresen** [GBIF-Europe/Regional-helpdesk#2]
A new ECA data publisher from Italy is asking for support with data publishing

University of Modena and Reggio E.
https://www.gbif.org/publisher/0a7d86c5-b9ab-4804-b1bd-ef1334bdc7ad

Point of contact 
Matteo Dal Zotto [matteo.dalzotto@unimore.it](mailto:matteo.dalzotto@unimore.it) & [dalzotto.matteo@yahoo.com](mailto:dalzotto.matteo@yahoo.com)

Maybe @DimEvil or @jholetschek have the opportunity to ask if they want support to use the [ECA IPT](https://cloud.gbif.org/eca)?

**Comment by dagendresen** [comment]
Assuming that the University of Modena and Reggio E. has received the support requested - and closing this old issue.

**Comment by spalp** [comment]
I do not believe they received a support. Should I contact them?

**Comment by jholetschek** [comment]
I've found a mail from Dimi from Feb 4, 2022. But after that, nothing happened, it seems.
