### ISSUE TITLE
Ukrainian datasets to move to the ECA cloud IPT

### ISSUE THREAD

**Issue by rukayaj** [GBIF-Europe/Regional-helpdesk#4]
With the destruction of the UA ipt server, we are in the process of moving Ukrainian data onto the ECA cloud IPT. The dwca backup from January is here: https://static.gbif.no/IPT_Karazin_UA_backup_2022-01-21.zip.

There are 107 files in here, but 111 datasets published on GBIF.  The four missing datasets from the backup are:
https://gbif.org/dataset/dc0167b0-0bec-40cc-bbf7-ec353baa73a7
https://gbif.org/dataset/4862b73e-8e93-42ad-b700-832ebcf5c328
https://gbif.org/dataset/c6a8b583-ba37-4a33-8d47-94119d1ab9c5
https://gbif.org/dataset/4f5a8595-6bda-4a3b-9d07-c0cdc38ffdef

**Comment by rukayaj** [comment]
There are 15 ukranian publishers we're going to need to add, but hopefully we can use the watchdog to add the dwca backups, see https://github.com/gbif/watchdog/wiki/OrphanedDatasets#user-content-how-to-re-publish-a-rescued-dataset-using-the-ipt

**Comment by dagendresen** [comment]
The [Ukrainian Scientific Centre of Ecology of the Sea](https://www.gbif.org/publisher/b9a1023a-e508-4168-a837-fa0781820a8b) ([UkrSCES](https://registry.gbif.org/organization/b9a1023a-e508-4168-a837-fa0781820a8b)) in Odesa is [hosting 10 datasets](https://registry.gbif.org/organization/b9a1023a-e508-4168-a837-fa0781820a8b/publishedDataset). This [IPT is still operational](http://gp.sea.gov.ua:8082/ipt/), but might be useful to be prepared if needed to secure it as well? http://gp.sea.gov.ua:8082/ipt/

**Comment by dagendresen** [comment]
Assuming that all the datasets that can be have now been recovered and transferred - and thus closing this old issue.
